name: Build and upload artifact

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install depends
        run: sudo apt-get install -y mingw-w64 clang
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu
          override: true
          components: rust-src
      - name: Make
        run: |
          make dist-no-7z
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: out/
